name: sivegeo-core
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip

  - numpy>=2.3
  - pandas>=2.3
  - polars>=1.40
  - scikit-learn>=1.7
  - prophet
  - xgboost
  - geopandas
  - shapely
  - streamlit
  - plotly
  - mlflow
  - pyyaml
  - requests
  - pytest
  - pytest-cov>=7.0
  - sentry-sdk
  - hypothesis
  - ipykernel>=6.30
  - python-dotenv

  - pip:
      - -e .
      - pysus==1.0.1
      - geobr
      - booktype