[[pages]]
path = "pages/indicators_page.py"
name = "Indicadores"
icon = "🏠"

[[pages]]
path = "pages/kpis_page.py"
name = "KPIS"
icon = ":books:"
url_path = "my_books"

[[pages]]
path = "pages/ranking_page.py"
name = "Ranking"
icon = ":books:"

[[pages]]
path = "pages/piramid_page.py"
name = "Piramide Etaria"
icon = ":books:"

[[pages]]
path = "pages/historic_evolution_page.py"
name = "Evolucao Historica"
icon = "🏠"

[[pages]]
path = "pages/forecast_page.py"
name = "Previsao de Tendencias - Dimensao Analitica"
icon = "🏠"

[[pages]]
path = "pages/radar_page.py"
name = "Radar"
icon = "🏠"

[[pages]]
path = "pages/heatmap_page.py"
name = "Mapa de Intensidade"
icon = "🏠"